export const CONTENT_RULES = {
  shortDuration: {
    minSeconds: 18,
    maxSeconds: 45,
    // Canonical cold-start / growth playbook: 22–30s micro-stories
    preferredMin: 22,
    preferredMax: 30,
  },
  longForm: {
    // Growth System v2 — trust-building window
    preferredMinMinutes: 8,
    preferredMaxMinutes: 12,
    chapterMin: 4,
    chapterMax: 6,
    coldOpenCuriositySeconds: 5,
    coldOpenStakesSeconds: 15,
    coldOpenJourneySeconds: 30,
    scriptPassThreshold: 90,
    shortsPerLong: { min: 3, max: 5 },
    titleMaxCharsPreferred: 60,
  },
  format: {
    aspectRatio: "9:16",
    width: 1080,
    height: 1920,
  },
  structure: {
    hookSeconds: 1.5,
    setupEndSeconds: 6,
    revealEndSeconds: 27,
    ctaTailSeconds: { min: 1, max: 2 },
  },
  captions: {
    maxLines: 2,
    safeMarginPercent: 12,
    highlightScientificTerms: true,
  },
  qualityWeights: {
    hookStrength: 20,
    standaloneClarity: 15,
    curiosity: 15,
    scientificAccuracy: 15,
    pacing: 10,
    visualPotential: 10,
    payoff: 10,
    ctaSubtlety: 5,
  },
  avoidPhrases: [
    "hey guys",
    "smash that like",
    "like and subscribe",
    "you won't believe",
    "gone wrong",
    "welcome to",
    "have you ever wondered",
    "for centuries",
    "what is a",
    "in this video",
  ],
  softCtas: [
    "Follow Orbit for the next mystery.",
    "More cosmic mysteries with Orbit.",
    "There is one reason scientists fear this. Orbit finds it in the full documentary.",
    "What Orbit discovers next changes the whole story.",
  ],
  hookCategories: [
    "mystery",
    "surprising_fact",
    "direct_question",
    "scale_comparison",
    "future_scenario",
    "existential_idea",
    "contrarian_statement",
    "scientific_reveal",
  ] as const,
  clipProposalCount: { min: 4, max: 8 },
  pipelineStages: [
    "Long Video",
    "Clip Ideas",
    "Approved Clips",
    "Editing",
    "Exported",
    "Platform Copy",
    "Scheduled",
    "Published",
    "Analysed",
  ] as const,
  publishItemStatuses: [
    "Draft",
    "Building",
    "Awaiting VO",
    "Awaiting render",
    "Awaiting review",
    "Ready",
    "Scheduled",
    "Published",
    "Reserve",
    "Held",
    "Rebuild required",
    "Blocked",
  ] as const,
  scheduleDisplayFields: [
    "cluster",
    "contentType",
    "publicationDate",
    "publicationTime",
    "relatedLongForm",
    "experimentId",
    "duration",
    "status",
    "releaseGateStatus",
    "reserveStatus",
    "youtubeVideoId",
    "replacementUploadStatus",
  ] as const,
} as const;

export type HookCategory = (typeof CONTENT_RULES.hookCategories)[number];
