#!/bin/zsh
# Part 05 retakes after t1 UAT: 05 walks off, 07 lightning, 08 ECG zigzag, 14 cuff morph + extra arm, 16 helix strands, 18 helixes.
S=/Users/benjaminoats/YouTube/hos-005-blood/02_Video-Projects/005_How-Harvey-Proved-Blood-Circulates/04_Generated-Clips/part05/refs/v02_vertex_stills
L=/Users/benjaminoats/YouTube/hos-005-blood/02_Video-Projects/005_How-Harvey-Proved-Blood-Circulates/07_Edit-Project/_logs/p05
M=/tmp/h5/m
NOTEXT="No letters, words, numbers or writing anywhere in the picture."
CALM="The figure stays still, faceless, and keeps its shape. Thin smooth lines only; no sparks, lightning, zigzags, spirals, twisted or ladder shapes, no blobs, balloons or tubes."
mint() { local id=$1 still=$2; shift 2; $M --part 5 mint $id --still $S/$still --framing try2 "$@" > $L/${id[1,2]}_t2.log 2>&1 & sleep 4 }

mint 05_explorer_scope 05_explorer_scope_v01.jpg --replace "He acts, then leaves. He leans in to the brass microscope, adjusts his round glasses, looks, then pulls back with a gasp.=>He stays at the table the whole time. He leans in to the brass microscope, adjusts his round glasses, looks, then lifts his head with a gasp of wonder and looks back down into it." --extra "Exactly one Explorer, on model the whole time: round thin gold glasses, messy wavy brown hair, teal coat. He never stands up, turns away or walks off; the camera holds and drifts in slowly. No flames. $NOTEXT"
mint 07_capillaries_loop 07_capillaries_loop_v02.jpg --replace "they light up with a soft glow as the blood creeps through, then the camera pulls back and the glowing mesh becomes the missing link in the glowing loop: heart, arteries, capillaries, veins, and the loop closes.=>tiny red cells drift slowly through them in single file from the small artery and come out blue into the small vein; the single hair stays still across the top for scale while the camera drifts slowly in." --extra "Flat ink-and-watercolour look on parchment; nothing glows, nothing flashes, the vessels keep exactly their shape and no new branches grow. $CALM $NOTEXT"
mint 08_your_blood 08_your_blood_v01.jpg --extra "Soft red light flows smoothly out from the heart down the arms and legs, crosses a fine soft mesh in the hands and feet, and flows back as blue up to the heart, round and round. Everything stays inside the body outline: no lines leave the hands, no heartbeat-monitor lines. The camera drifts in slowly. $CALM $NOTEXT"
mint 14_cuff_release 14_cuff_release_v02.jpg --extra "The grey cuff keeps exactly its shape and slowly loosens round the upper arm; the round metal stethoscope disc slides down to the inside of the elbow and rests there, listening. Only the patient's one bare arm and the stethoscope: no second arm, no sleeve, no other hand enters the picture. No face. $NOTEXT"
mint 16_proved_last_link 16_proved_last_link_v02.jpg --replace "Harvey's painted heart chart; a glowing loop draws itself over it and runs round, and at the far end the last link, a fine glowing mesh of tiny vessels, lights up softly to close it.=>Harvey's painted heart chart on the oak table: a soft red and blue ring runs slowly round the painted heart, and at one point of the ring a small gap fills with a fine net of tiny lines that lights up softly and closes the ring." --extra "Everything stays on the page inside the ring: no strands, ribbons, waves or lines trail off the page. No sparkles, glitter, dust, particles or sparks. No hands. The painted heart stays exactly as it is. $NOTEXT"
mint 18_pond_life 18_pond_life_v01.jpg --replace "(rods, spheres, spirals)=>(little rods and round cells)" --extra "Inside the round bright drop, tiny faceless single-celled creatures swim, wriggle and tumble all the time, alive. No spirals, coils, twisted or ladder shapes. No faces, eyes or mouths on anything. $NOTEXT"
wait
echo P05_MINT_B_DONE
