#!/bin/zsh
# Part 05 start frames. Loop plates seed from Part 03's KEEP loop figure (continuity);
# 16 from Part 01's heart chart; 05 from 04 (same study); 14 from 13 (same arm).
F=/Users/benjaminoats/YouTube/hos-005-blood/02_Video-Projects/005_How-Harvey-Proved-Blood-Circulates/04_Generated-Clips
S=$F/part05/refs/v02_vertex_stills
M=/tmp/h5/m
latest() { ls -t $S/$1_v*.jpg 2>/dev/null | head -1 }
NOTEXT="No letters, words, numbers or writing anywhere in the picture."
FIG=$S/_p03_12t2_at4.jpg
CLOSE=$S/_p03_13t3_at4.jpg
CALM="Clean and calm: thin smooth glowing lines inside the figure; no sparks, lightning, spirals, twisted or ladder shapes, no blobs or balloons, no eyes or face."
NOFLAME="Soft warm daylight from a window out of frame; no candles, sconces, lamps or flames anywhere."

$M --part 5 still 04_malpighi_slide --extra "Bologna, 1661: Marcello Malpighi, a man of about thirty-three with a readable friendly face, long dark curled wig, brown 1660s coat and white cravat, sits at a small brass microscope on a desk by a bright window, holding a thin clear glass slide with a pale pink film on it near the stage. Plain plaster and wood study. No animals. $NOFLAME $NOTEXT"
$M --part 5 still 05_explorer_scope --seed $(latest 04_malpighi_slide) --extra "The same Bologna study and brass microscope by the bright window; Malpighi has stepped back out of frame. Exactly one Explorer, the young boy with messy wavy brown hair, round thin gold glasses, long teal coat, tan waistcoat and brown bow tie, leans in to the microscope eyepiece. $NOFLAME $NOTEXT"
$M --part 5 still 01_loop_gap --seed $FIG --extra "The same faceless translucent standing figure in the same oak-panelled room, with its red arteries and blue veins forming one glowing loop through the body; down at the hands and feet the red lines end and the blue lines start, but they do not meet: a small dark gap at each end where the glow fades out. $CALM $NOFLAME $NOTEXT"
$M --part 5 still 08_your_blood --seed $FIG --extra "The same faceless translucent standing figure in the same oak-panelled room, the full circuit lit: red arteries out from the heart, a fine soft glowing mesh at the hands and feet, blue veins back to the heart, one closed loop. $CALM $NOFLAME $NOTEXT"
$M --part 5 still 10_one_vein --seed $FIG --extra "The same faceless translucent standing figure in the same oak-panelled room with its red and blue loop glowing softly; at the inside of the left elbow a small soft pale-blue glow sits in one vein. $CALM $NOFLAME $NOTEXT"
$M --part 5 still 09_question --seed $CLOSE --extra "Closer on the chest of the same faceless translucent figure: the clean red cartoon heart in the middle with red arteries and blue veins leading out and back. No ring, no circle, no sand-glass, no clock. $CALM $NOFLAME $NOTEXT"
$M --part 5 still 07_capillaries_loop --seed $CLOSE --style-ref $CLOSE --extra "Very close, magnified: a fine net of tiny soft red-to-blue vessels, thinner than hairs, joining one small red artery on the left to one small blue vein on the right, against a soft warm dark background; a single straight brown human hair lies across the top for scale, much thicker than the vessels. $CALM $NOTEXT"
$M --part 5 still 06_eyepiece_mesh --seed $(latest 07_capillaries_loop) --extra "The view through a 17th-century microscope eyepiece: a soft round bright circle in a dark vignette, inside it a pale pink thin film with a fine net of tiny vessels joining a red artery to a blue vein. Daylight look, nothing glowing. $NOTEXT"
$M --part 5 still 02_tiny_gaps --extra "A soft, warm, blurred magnified view of pale pink flesh texture with a red artery fading out on the left and a blue vein starting on the right and only a soft uncertain haze between them, nothing sharp, nothing glowing. No wounds, no blood on skin, no gore. $NOTEXT"
$M --part 5 still 03_old_harvey --extra "London in the 1650s: old William Harvey, about seventy-five, white hair to the collar and small white pointed beard, the same olive skin and dark eyes, black gown with a plain white falling collar, stands at a leaded window in soft warm afternoon light holding a small closed leather book. $NOFLAME $NOTEXT"
$M --part 5 still 11_transfusion --extra "A 1660s physicians' room: two physicians in long curled wigs and dark coats bend over a plain oak table with a slender silver tube, a quill and an empty pewter bowl laid out on linen. Tools only: no animal, no patient, no blood. $NOFLAME $NOTEXT"
$M --part 5 still 12_tools --seed $(latest 11_transfusion) --extra "Close on the same table: a slender silver tube and two quills laid on white linen beside an empty pewter bowl; at the edge, a hand in a dark cuff rests a quill on a ledger whose page is seen edge-on, nothing readable. No blood. $NOFLAME $NOTEXT"
$M --part 5 still 13_cuff --extra "A bright clean modern clinic: a plain grey blood pressure cuff wrapped round a bare upper arm resting on a white table, the rubber tube running out of frame; arm only, no face, no other people. Clean skin. $NOTEXT"
$M --part 5 still 14_cuff_release --seed $(latest 13_cuff) --extra "The same arm and clinic: the grey cuff sits loose on the upper arm, and the round metal disc of a stethoscope rests at the inside of the elbow, held by a gloved fingertip. Arm only, no face. $NOTEXT"
$M --part 5 still 15_band_table --extra "Still life on an old dark oak table in soft warm daylight: a plain strip of cream linen lies coiled in front; behind it a page of handwritten sums lies soft and out of focus so nothing on it can be read; beside it an old brown-ink drawing of a vein with small paired paper flaps. $NOFLAME No readable letters, words or numbers anywhere."
$M --part 5 still 16_proved_last_link --seed $F/part01/refs/v02_vertex_stills/09_heart_clock_v02.jpg --extra "The same painted red heart on the cream page on the dark oak table, seen from above; no watch, no clock, no hands. A thin red line and a thin blue line are painted leaving and returning to the heart in an open loop; at the far end a small gap between them. $NOFLAME $NOTEXT"
$M --part 5 still 17_dutch_lens --extra "Delft, 1670s: a cloth merchant's hand with a plain linen cuff holds a tiny brass lens plate up towards a bright leaded window; beside it on the sill a thin glass sliver with a single clear drop of pond water. Hand only, no face. $NOFLAME $NOTEXT"
$M --part 5 still 18_pond_life --extra "Through an old lens: a bright round drop of pond water in a soft dark vignette, full of tiny simple faceless shapes in soft greens and golds: little rods, small spheres and tiny spirals, softly glowing, like living specks. No faces, eyes or mouths on anything. $NOTEXT"
echo P05_STILLS_A_DONE
